language: node_js

node_js:
  - "8.10.0"

before_install:
  - npm install -g node-gyp

before_script:
  - psql -c 'create database "piikki-test";' -U postgres

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

env:
  - CXX=g++-5

services:
  - postgresql
